In [1]:
import torch
print(torch.__version__)

2.9.1+cu130


In [6]:
if torch.cuda.is_available():
    print("GPU available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

GPU available.
Using GPU: NVIDIA GeForce RTX 5070 Ti


# Creating Tensor

In [ ]:
et = torch.empty(2, 3)
print(et)

tensor([[-1.2417e-26,  3.3645e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


torch.Tensor

In [ ]:
z = torch.zeros(2, 3)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.Tensor

In [ ]:
o = torch.ones(2, 3)
print(o)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [44]:
r = torch.rand(2, 3)
print(r)

tensor([[0.4340, 0.1371, 0.5117],
        [0.1585, 0.0758, 0.2247]])


In [ ]:
torch.manual_seed(42)
rs = torch.rand(2, 3)
print(rs)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
t = torch.tensor([[1 , 2, 3],[5, 6, 7]])
print(t)

tensor([[1, 2, 3],
        [5, 6, 7]])


In [47]:
print("using  arange-> ", torch.arange(0, 10, 2))

print("using linspace -> ", torch.linspace(1, 10 ,10))

print("using eye -> ", torch.eye(5))

print("using full -> ", torch.full((3, 3), 5))

using  arange->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [49]:
x = rs.shape
x

torch.Size([2, 3])

In [ ]:
torch.empty_like(et)

tensor([[-1.2521e-26,  3.3645e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  3.3652e-41]])

In [73]:
torch.ones_like(o)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [74]:
torch.zeros_like(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [91]:
torch.rand_like(r)

tensor([[0.4751, 0.1985, 0.1941],
        [0.0521, 0.3370, 0.6689]])

# Tensor Data Types

In [92]:
rs.dtype

torch.float32

In [ ]:
torch.tensor([1.0, 2.0, 3.85], dtype = torch.int64)

tensor([[1., 2., 3.],
        [5., 6., 7.]], dtype=torch.float64)

In [99]:
torch.tensor([1, 2, 3], dtype = torch.float32)

tensor([1., 2., 3.])

In [100]:
t.to(torch.float64)

tensor([[1., 2., 3.],
        [5., 6., 7.]], dtype=torch.float64)